# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7a0e194af3cf08256776fcc84e805cd6380f563f4e7013a82a5ebcae4d810e2570b127e6dbda8da59f9e61b5b1792ad6e918005f194056fb88b0bf0dea8b8d

test:
  secret_key_base: ce0fe885febf2845d1cd5698c586c0a9f8903ef1de838da1b2149d6cc3de3de4f9504e7bf1bdf79452c62f8038aa3c0c4f2b3a7d232a2e8accf1405a6e2180b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
